### ISSUE TITLE
synth.tcl has hardcoded paths

### ISSUE THREAD

**Issue by kkumar23** [QuickLogic-Corp/symbiflow-arch-defs#122] opened 2020-08-13 17:58 UTC
Couple of issues:
1) Synth.tcl has the path hardcoded "source $::env(symbiflow-arch-defs_SOURCE_DIR)/quicklogic/pp3/yosys/pack.tcl" , this does not work with Symbiflow installer
2) The variable has symbiflow-arch-defs_SOURCE_DIR, character '-' is not supported , we can use '_'.
3) Add pack.tcl in the installation as well

**Comment by mkurc-ant** [comment] 2020-08-19 16:06
With the PR merged the issue is fixed. The `pack.tcl` is now installed alongside with other scripts. It is invoked using TCL script path discovery so no need for env variable lookup.

**Comment by kkumar23** [comment] 2020-08-26 08:30
fixed

**Closed** 2020-08-26 08:29 UTC
