### ISSUE TITLE
SDF/Post Layout simulation

### ISSUE THREAD

**Issue by lnsharma** [QuickLogic-Corp/symbiflow-arch-defs#236] opened 2021-05-03 09:01 UTC
Define verilog models in Symbiflow to enable sdf/post layout simulation. Also, generate sdf file require for post layout simulation.

**Comment by kkumar23** [comment] 2021-05-20 12:05
Duplicate of #259

**Comment by mkurc-ant** [comment] 2021-06-02 07:24
With https://github.com/QuickLogic-Corp/symbiflow-arch-defs/pull/273 merged it is now possible to get post layout Verilog netlist and SDF file and use it eg. with Icarus Verilog.

**Closed** 2021-06-02 18:33 UTC
