### ISSUE TITLE
fasm2bels.py shows up errors

### ISSUE THREAD

**Issue by kkumar23** [QuickLogic-Corp/symbiflow-arch-defs#103] opened 2020-08-03 12:32 UTC
Run designs : QuickLogic-testsuit/ram_test or fifo_test for target bit_v/analysis

Symbiflow shows the below error:
 File "/home/travis/build/QuickLogic-Corp/symbiflow-arch-defs/quicklogic/common/utils/fasm2bels.py", line 1048, in <module>
17680    verilog, pcf, qcf = f2b.convert_to_verilog(fasmlines)
17681  File "/home/travis/build/QuickLogic-Corp/symbiflow-arch-defs/quicklogic/common/utils/fasm2bels.py", line 954, in convert_to_verilog
17682    self.resolve_global_clock_network()
17683  File "/home/travis/build/QuickLogic-Corp/symbiflow-arch-defs/quicklogic/common/utils/fasm2bels.py", line 915, in resolve_global_clock_network
17684    qmux_map = self.resolve_qmux(gmux_map)
17685  File "/home/travis/build/QuickLogic-Corp/symbiflow-arch-defs/quicklogic/common/utils/fasm2bels.py", line 843, in resolve_qmux
17686    gmux_loc, gmux_cell, gmux_pin = sel_map[sel]
17687KeyError: 1

**Comment by mkurc-ant** [comment] 2020-08-19 16:08
The PR is merged and the issue solved. The cause was lack of definition of some connections to QMUX in fasm2bels.

**Closed** 2020-08-26 08:30 UTC
